name: shearXlensing
channels:
  - conda-forge
  - defaults
dependencies:
  - healpy
  - matplotlib
  - numpy
  - pyccl
  - namaster
  - python
  - scipy
  - ipykernel
  - h5py
  - fitsio
  - joblib
  - tqdm
  - sacc
  - emcee
  - cosmosis
  - cosmosis-build-standard-library
  - getdist
  - astropy
  - pyyaml
