name: shearXlensing
channels:
  - conda-forge
  - defaults
dependencies:
  - healpy
  - matplotlib
  - namaster
  - numpy
  - pyccl
  - python
  - scipy==1.13.1
  - ipykernel
  - h5py
  - fitsio
  - joblib
  - tqdm
  - sacc
