nside: 1024
# constructs linear bins between ell_min and 3*nside with delta_ell spacing
ell_min: 100
delta_ell: 300
# place to save namaster workspaces
workspace_dir: "/projects/caps/aaronjo2/shearXlensing/workspaces"

# specify tracers
# each tracer can have multiple tomographic bins
# can use python format strings to specify location of maps/masks
#   known variables: bin and nside
tracer_wl:
    name: "DES-Y3 shear"
    bins: 4
    data_dir: "/projects/caps/aaronjo2/shearXlensing/data/des_y3/maps"
    map: "DESY3_zbin{bin}_nside{nside}_shearmaps.fits"
    mask: "DESY3_zbin{bin}_nside{nside}_mask.fits"
    # Fix sign convention for e1/e2 to that of Q/U: (e1, e2) -> (-e1, e2)
    correct_qu_sign: True

tracer_ck:
    name: "SPT-3G CMB convergence"
    data_dir: "/projects/caps/aaronjo2/shearXlensing/data/spt"
    map: "kmapxx_0_mfhalf1_{nside}.fits"
    mask: "mask{nside}_border_apod_mask.fits"
    # square mask for CMB lensing field
    use_mask_squared: True

# specify sets of cross-spectra (and corresponding covariances) to calculate
cross_spectra:
    # specific x-spectra to calculate given as tuples of 2 tracers
    list:
        - [tracer_wl, tracer_ck]
    # calculate covariance
    covariance: True
    interbin_cov: True
    # save all cls and covs in a .npz file
    # simply dumps full namaster output without any post-processing
    save_npz: "cross_spectra_nside{nside}.npz"
    # save select cls and their full cov (+ tracer info) in a sacc file
    save_sacc:
        ignore_b_modes: True
        metadata:
            description: "SPT-3G CMB lensing X DES-Y3 shear"
        file: "cross_spectra_nside{nside}.fits"

#cross_spectra_psf:
#    list:
#        - [tracer_wl_psf, tracer_ck]
#    covariance: True
